# Generated by Django 4.2.6 on 2023-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('mobile', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
