# Generated by Django 4.2.6 on 2023-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
    ]
