# Generated by Django 4.2.6 on 2023-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_alter_datas_age_alter_datas_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(default='', max_length=50)),
                ('Password', models.IntegerField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Datas',
        ),
    ]
