# Generated by Django 4.2.6 on 2023-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_login_delete_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField(default='')),
                ('Email', models.CharField(default='', max_length=50)),
                ('Phone', models.IntegerField(default='')),
            ],
        ),
    ]
