# Generated by Django 4.2.6 on 2023-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Age',
            field=models.PositiveIntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
